
import React from "react";
import Image from "next/image";

import Link from "next/link";
export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

async function getProductDetails(id) {
  const res = await fetch(`https://api.escuelajs.co/api/v1/products/${id}`);
  const data = await res.json();
  return data;
}

export async function generateMetadata({ params }) {
  
  const { id } = params;
  const product = await getProductDetails(id);
  return {
    title: product.title,
    description: product.description,
    metadataBase: new URL("https://istad.co"),
    alternates: {
      canonical: "/", // canonical mean the original page
      languages: {
        "en-US": "/en-US", 
        "de-DE": "/de-DE",
      },
      
    },
    openGraph: {
      images: product.images[0],
    },
  };
}
export default async function ProductDetails({ params }) {
  const { id } = params;
  const product = await getProductDetails(id);
  return (
       <div className="mt-32">
        <div className="sm:mb-10 lg:grid lg:grid-cols-5 md:grid-cols-none md:bg-gray-300 bg-gray-300 lg:bg-white lg:h-full  p-24">
          <div className=" px-10 py-10 max-w-md m-auto lg:col-span-2 mt-20 mb-20 shadow-xl rounded-xl lg:mt-10 md:shadow-xl md:rounded-xl lg:shadow-none lg:rounded-none lg:w-full lg:mb-10 lg:px-5 lg:pt-5 lg:pb-5 lg:max-w-lg bg-white ">
            <div class="font-semibold text-xl mb-4">
               {product.id?product.id :"can not found id"}
            </div>
            <h1 className="mt-5 font-bold text-lg lg:mt-7">
              {product.title?product.title:"product can't find"}
            </h1>
            <h1 className="font-bold text-lg text-gray-600">

            </h1>
            <h1 className="text-lg text-gray-600 text-justify pt-2">
              {product.description?product.description:"product can't find"}
            </h1>
            <Link href="/" 
            className="mt-10 bg-gray-600 px-10 shadow-2xl rounded-xl text-white font-bold hover:bg-gray-800">
              Go Back
            </Link>
          </div>
    
          <div className="hidden relative lg:block lg:col-span-3">
              {product.images&&(
                  <Image
                  className="absolute inset-0 w-full h-full object-cover object-center" 
                  src={product.images[0]}
                  alt="Ad- woman on a beach"/>
              )}
          </div>
        </div>
        </div>
  );
}
